#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -x
#set -eu
set -o pipefail


#############################################################
# 0- Pre-Installation
#############################################################

# NVIDIA_TMP_FOLDER=/tmp/yum
mkdir -p /root/tmp
NVIDIA_TMP_FOLDER=/root/tmp

yum install -y mesa-libGLES.x86_64
yum install -y mesa-libGL-devel.x86_64
yum install -y mesa-libGLU-devel.x86_64
yum install -y mesa-libGLw.x86_64
yum install -y mesa-libGLw-devel.x86_64
yum install -y libXi-devel.x86_64
yum install -y freeglut-devel.x86_64
yum install -y freeglut.x86_64

#############################################################
# I- Installation (runfile)
#############################################################

# Install wget
sudo yum install -y wget

# Install kernel headers
sudo yum install -y kernel-devel-$(uname -r) kernel-headers-$(uname -r)

# Get the NVIDIA Cuda Toolkit for Centos
wget http://developer.download.nvidia.com/compute/cuda/7.5/Prod/local_installers/cuda_7.5.18_linux.run

# Install the NVIDIA Cuda Toolkit for Centos
export TMPDIR=$NVIDIA_TMP_FOLDER
sudo sh cuda_7.5.18_linux.run --samples --toolkit --driver --silent --verbose -tmpdir $NVIDIA_TMP_FOLDER

#############################################################
# III- Post-Installation
#############################################################

# Mandatory Actions
echo 'export PATH=/usr/local/cuda-7.0/bin:$PATH' > /etc/environment
echo 'export LD_LIBRARY_PATH=/usr/local/cuda-7.0/lib64:$LD_LIBRARY_PATH' > /etc/environment

# Compile example
DEVICE_QUERY_PATH="/usr/local/cuda-7.5/samples/1_Utilities/deviceQuery"
source /etc/environment
pushd $DEVICE_QUERY_PATH
sudo make
popd

# Generate startup script that load information from nvdia device query
cat > /etc/load_nvidia_info <<- EOM
#!/bin/bash
DEVICE_QUERY_PATH="$DEVICE_QUERY_PATH"
OUTPUT_FILE_PATH="/opt/nvidia.txt"

pushd \$DEVICE_QUERY_PATH
./deviceQuery > \$OUTPUT_FILE_PATH
chmod 777 \$OUTPUT_FILE_PATH
popd

EOM

# Add startup script that load information from nvdia device query
chmod ugo+x /etc/load_nvidia_info
echo "bash /etc/load_nvidia_info" >> /etc/rc.local

# Ensure that /etc/rc.local is executable
sudo chmod +x /etc/rc.local

#############################################################
# IV- Cleaning
#############################################################

exit 0

